---
title: "b12_levels"
output: html_document
date: "2025-06-09"
---

```{r}
#install.packages("googlesheets4)
library(googlesheets4) #scrapes google sheets
library(dplyr) # dataframe manipulation
library(ggplot2) # plotting package
library(lubridate)
library(tidyr)
library(scales)
library(growthrates)

```

```{r import data}
b12 <-as.data.frame(read_sheet("https://docs.google.com/spreadsheets/d/1RvnJ-K7zcXLj2GDZcDpJ9tp0e0vVyDev0dY1mT9sshw/edit?gid=0#gid=0")) 
# Remove periods and convert to numeric
b12$Time <- as.numeric(sub('.', '', b12$Time)) 
# Convert Date column to Date type
b12$Date <- ymd(b12$Date)
b12$Treatment <- unlist(b12$Treatment)
#covert timepoints to hours
b12$Time <- b12$Time * 48 #covert timepoints to hours

# put treatment level in desired order
b12 <- b12 %>%
  mutate(Treatment = factor(Treatment, levels = c(
    "369pM",    # Place the levels in desired order
    "36pM",
    "3.69pM",
    "0.369pM",
    "0.0369pM"
  )))

# Convert Time from hours to days
b12$Time_in_Days <- b12$Time / 24  # Convert Time from hours to days
```

```{r Summarize mean/sd}
combined_avg <- b12 %>%
  group_by(Time_in_Days,Treatment, Round) %>%
  summarise(
    mean_chl = mean(`Chlorophyll-A (RFU)`, na.rm = TRUE),
    sd_chl = sd(`Chlorophyll-A (RFU)`, na.rm = TRUE),
    .groups = "drop"
  )
```


```{r plot growth}
combined_avg  %>% 
  ggplot(aes(x = Time_in_Days, y = mean_chl, color = Treatment)) + 
  geom_point() + 
  geom_smooth(se = FALSE) + 
  facet_grid(Round ~ Treatment, scales = "free_y") +  
  labs(  
    x = "Time (days)",  
    y = expression(paste("Chlorophyll-", italic("a"), " fluorescence (RFU)")) 
  ) + 
  scale_x_continuous() +  
  scale_color_manual(values = c(  
    "0.0369pM" = "#102E50",   
    "0.369pM" = "#102E50",      
    "3.69pM" = "#102E50",   
    "36pM" = "#102E50",      
    "369pM" = "#102E50"      
  )) + 
  geom_errorbar(
    aes(ymin = mean_chl - sd_chl, ymax = mean_chl + sd_chl, group = Treatment),
    width = 0.3, color = "black", alpha = 0.6
  )  +
  
  # Points with white fill and colored outline
  geom_point(shape = 21, fill = "white", aes(color = Treatment), stroke = 1.2, size = 2) +
  theme_classic() +
  theme(
    legend.position = "none", 
    legend.key.size = unit(1.5, "cm"), 
    legend.title = element_text(size = 20), 
    legend.text = element_text(size = 20, color = "black"),
    # Ensure no background or border for legend
    legend.background = element_blank(), 
    legend.key = element_rect(color = "white"), 
    legend.box.background = element_rect(color = "white"),
    # Make sure no borders or backgrounds for the plot area and panel
    panel.background = element_rect(fill = NA, color = NA),
    plot.background = element_rect(fill = NA, color = NA),
    # Strip background adjustments
    strip.background = element_blank(),
    panel.border = element_rect(color = 'black', fill = NA),
    # Axis text and title styling
    axis.title.x = element_text(size = 20, color = "black"),  
    axis.title.y = element_text(size = 20, color = "black"),  
    axis.text.x = element_text(size = 16, color = "black"),  
    axis.text.y = element_text(size = 16, color = "black"),  
    # Plot title and strip text formatting
    plot.title = element_text(size = 20, face = "bold"),  
  ) +
  guides(color = guide_legend(override.aes = list(fill = NA))) 

# ggsave("b12_lev_final.png", width = 10, height = 7)
```
```{r plot growth for presentation}
b12  %>% 
  ggplot(aes(x = Time_in_Days, y = `Chlorophyll-A (RFU)`, color = Treatment)) + 
  geom_point() + 
  geom_smooth(se = FALSE) + 
  facet_grid(Round ~ Treatment, scales = "free_y") +  
  labs(  
    x = "Time (days)",  
    y = expression(paste("Chlorophyll-", italic("a"), " fluorescence (RFU)")) 
  ) + 
  scale_x_continuous() +  
  scale_color_manual(values = c(  
    "0.0369pM" = "#102E50",   
    "0.369pM" = "#102E50",      
    "3.69pM" = "#102E50",   
    "36pM" = "#102E50",      
    "369pM" = "#102E50"      
   )) + 
  # geom_errorbar(
  #   aes(ymin = mean_chl - sd_chl, ymax = mean_chl + sd_chl, group = Treatment),
  #   width = 0.3, color = "black", alpha = 0.6 +
    
  
  # Points with white fill and colored outline
 # geom_point(shape = 21, fill = "white", aes(color = Treatment), stroke = 1.2, size = 2) +
  theme_classic() +
  theme(
    legend.position = "none", 
    legend.key.size = unit(1.5, "cm"), 
    legend.title = element_text(size = 20), 
    legend.text = element_text(size = 20, color = "black"),
    # Ensure no background or border for legend
    legend.background = element_blank(), 
    legend.key = element_rect(color = "white"), 
    legend.box.background = element_rect(color = "white"),
    # Make sure no borders or backgrounds for the plot area and panel
    panel.background = element_rect(fill = NA, color = NA),
    plot.background = element_rect(fill = NA, color = NA),
    # Strip background adjustments
    strip.background = element_blank(),
    panel.border = element_rect(color = 'black', fill = NA),
    # Axis text and title styling
    axis.title.x = element_text(size = 25, color = "black"),  
    axis.title.y = element_text(size = 25, color = "black"),  
    axis.text.x = element_text(size = 20, color = "black"),  
    axis.text.y = element_text(size = 20, color = "black"),  
    # Plot title and strip text formatting
    plot.title = element_text(size = 25, face = "bold"), 
   strip.text.x.top  = element_text(size = 25)
  ) +
  guides(color = guide_legend(override.aes = list(fill = NA))) 

 ggsave("b12_lev_pres.png", width = 10, height = 7)
```
```{r ANOVA of `Chlorophyll-A (RFU)` among B12 levels and post-hoc multiple comparisons }
TreatExp_aov <- aov(`Chlorophyll-A (RFU)` ~ Treatment , data = b12)
summary(TreatExp_aov)

TukeyHSD(TreatExp_aov, conf.level=.95)
#Chl-a values were not significantly different for 36pM-369pM  (padj. 0.2451286 )
```
`

```{r calculate mean max growth rate (µmax)}
# group by serial transfer and media treatment 
b12 %<>%
  group_by( Treatment) %>%
  filter(n() > 4) %>%
  ungroup() %>%
  droplevels() 
  
#find max growth rate/ spar 0.7 allowed for a better representation of the treatments
many_spline_fits <- all_splines(`Chlorophyll-A (RFU)` ~ Time_in_Days| Treatment + Bio_Rep,
                                data = b12, spar = 0.7)

par(mfrow = c(4, 6))
par(mar = c(2.5, 4, 2, 1))
plot(many_spline_fits)

all_fits <- many_spline_fits@fits

# Loop through and extract mumax and y0
b12_mumax <- data.frame(
  ID = names(all_fits),
  y0 = sapply(all_fits, function(fit) fit@par["y0"]),
  mumax = sapply(all_fits, function(fit) fit@par["mumax"])
)

# View the result
print(b12_mumax)
```

```{r calculate mean max growth rate and plot with relabled plots for paper}

# b12 %<>%
#   droplevels() %>%
#   mutate(Treatment_Rep = paste0(Treatment, " Rep ", Bio_Rep, "")) %>%
#   group_by(Treatment_Rep) %>%
#   filter(
#     all(!is.na(`Chlorophyll-A (RFU)`)),
#     all(`Chlorophyll-A (RFU)` > 0),
#     n() >= 4
#   ) %>%
#   ungroup()
# 
# # Fit splines
# many_spline_fits <- all_splines(
#   `Chlorophyll-A (RFU)` ~ Time_in_Days | Treatment_Rep,
#   data = b12,
#   spar = 0.5
# )
# 
# # Plot
# par(mfrow = c(5, 3))
# par(mar = c(2.5, 4, 2, 1))
# plot(many_spline_fits)
# 
# # Extract y0 and mumax
# all_fits <- many_spline_fits@fits
# 
# b12_mumax <- data.frame(
#   Treatment_Rep = names(all_fits),
#   y0 = sapply(all_fits, function(fit) fit@par["y0"]),
#   mumax = sapply(all_fits, function(fit) fit@par["mumax"])
# ) %>%
#   separate(Treatment_Rep, into = c("Treatment", "Rep"), sep = ":", remove = FALSE)
# 
# # View result
# print(b12_mumax)

```

```{r prepare data for ANOVA}
# Clean `b12_mumax`
b12_mumax_clean <- b12_mumax %>%
  separate(ID, into = c("Treatment", "Replicate"), sep = ":", remove = FALSE) %>%
  mutate(Treatment = factor(Treatment, levels = c("369pM", "36pM", "3.69pM", "0.369pM", "0.0369pM")))
```

```{r ANOVA of µmax among b12 levels and post-hoc multiple comparisons}
aov_result <- aov(mumax ~ Treatment, data = b12_mumax_clean)
summary(aov_result)

TukeyHSD(aov_result)

#             Df   Sum Sq  Mean Sq F value  Pr(>F)   
# Treatment    4 0.025662 0.006416   7.421 0.00482 **
# Residuals   10 0.008646 0.000865                   
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
#   Tukey multiple comparisons of means
#     95% family-wise confidence level
# 
# Fit: aov(formula = mumax ~ Treatment, data = b12_mumax_clean)
# 
# $Treatment
#                          diff         lwr         upr     p adj
# 36pM-369pM       -0.008106788 -0.08711802  0.07090444 0.9967161
# 3.69pM-369pM     -0.023868361 -0.10287959  0.05514287 0.8521806
# 0.369pM-369pM    -0.048538432 -0.12754966  0.03047280 0.3224754
# 0.0369pM-369pM   -0.114887101 -0.19389833 -0.03587587 0.0051706
# 3.69pM-36pM      -0.015761573 -0.09477280  0.06324966 0.9614232
# 0.369pM-36pM     -0.040431644 -0.11944288  0.03857959 0.4834306
# 0.0369pM-36pM    -0.106780313 -0.18579154 -0.02776908 0.0084980
# 0.369pM-3.69pM   -0.024670071 -0.10368130  0.05434116 0.8372917
# 0.0369pM-3.69pM  -0.091018741 -0.17002997 -0.01200751 0.0230272
# 0.0369pM-0.369pM -0.066348669 -0.14535990  0.01266256 0.1124679

```

```{r mumax of B12 levels}
# calculate standard deviation and mean 
b12_summary <- b12_mumax_clean %>%
  group_by(Treatment) %>%
  summarise(
    mean_mumax = mean(mumax, na.rm = TRUE),
    se_mumax   = sd(mumax, na.rm = TRUE)/sqrt(n()),
    .groups = "drop"
  )

# plot data 
ggplot(b12_mumax_clean, aes(x = Treatment, y = mean_mumax, color = Treatment)) +
# add bars one standard devation from mean 
  geom_errorbar(data = b12_summary, 
                aes(x = Treatment, y = mean_mumax, 
                    ymin = mean_mumax - se_mumax, 
                    ymax = mean_mumax + se_mumax, 
                    color = Treatment),
                width = 0.2, linewidth = 0.8) +
  geom_point(data = b12_mumax_clean, 
             aes(x = Treatment, y = mumax, color = Treatment),
             size = 3,
             alpha = 0.6) + 

  scale_color_manual(values = c(  
    "0.0369pM" = "#102E50",   
    "0.369pM" = "#102E50",      
    "3.69pM" = "#102E50",   
    "36pM" = "#102E50",      
    "369pM" = "#102E50"      
  )) + theme_bw(base_size = 14) +
  theme(
    strip.background = element_blank(),
    strip.text = element_text(face = "plain"),
    axis.text.x = element_text(color = "black", size = 20),
    axis.text.y = element_text(color = "black", size = 20),
    legend.title = element_blank(),
    legend.text = element_blank(),
    legend.key = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.title.y = element_text(size = 20, face = "plain"),
    axis.title.x = element_text(size = 25, face = "plain"),
    panel.spacing = unit(.3, "cm")
  ) +
  labs(
    x = "Treatment",
    y = expression(paste("Maximum growth rate (", mu[max], ")"))
  )

 ggsave("b12mumax.png", width = 9, height =7)
```
```{r max biomass reached in each B12 concentration}
max_bio <- b12  %>%
  filter(Treatment %in% c(Treatment, levels = c("369pM", "36pM", "3.69pM", "0.369pM", "0.0369pM"))) %>%
  group_by(Treatment, Bio_Rep) %>% 
  summarise(Max_Chl = max(`Chlorophyll-A (RFU)`, na.rm = TRUE)) %>%
  ungroup()

print(max_bio)
```

```{r plot max biomass}
ggplot(max_bio, aes(x = Treatment, y = Max_Chl )) +
  stat_summary(fun.data = mean_sdl, fun.args = list(mult = 1), 
               geom = "pointrange",shape = 21, size = .5, fill = "white", color = "black", stroke = 1.2)  +
  geom_point(width = 0.1, size = 3, alpha = 0.6, color = "black") +
  scale_color_manual(values = c(
  "0.0369pM" = "#AFCBFF",  # Lightest blue (lowest concentration)
  "0.369pM"  = "#7FB2F0",  # Light blue
  "3.69pM"   = "#508CCF",  # Medium blue
  "36pM"     = "#2F5D9F",  # Darker blue
  "369pM"    = "#102E50"   # Deep navy (highest concentration)
)) + 
  theme_classic() +
  ylab(expression(paste("Maximum Chlorophyll-", italic("a"), " fluorescence achieved (RFU)"))) +
  xlab(expression(B[12]~Concentration~"(pM)")) + theme(
    strip.background = element_blank(),
    panel.border = element_rect(color = 'black', fill = NA),
    # Axis text and title styling
    axis.title.x = element_text(size = 25, color = "black"),  
    axis.title.y = element_text(size = 25, color = "black"),  
    axis.text.x = element_text(size = 20, color = "black"),  
    axis.text.y = element_text(size = 20, color = "black"),  
    
    # Plot title and strip text formatting
    plot.title = element_text(size = 25, face = "bold"),  
    strip.text = element_text(size = 25), 
  ) 

 ggsave("b12_lev_max_bio.png", width = 8, height =10)

```

```{r ANOVA of max biomass among B12 concentrations and post- hoc multiple comparisons}
result<- aov(Max_Chl~Treatment, max_bio)
summary(result)

TukeyHSD(result)

#            Df   Sum Sq  Mean Sq F value   Pr(>F)    
# Treatment    4 52576804 13144201   34.45 3.66e-06 ***
# Residuals   11  4197093   381554                     
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# > 
# > TukeyHSD(result)
#   Tukey multiple comparisons of means
#     95% family-wise confidence level
# 
# Fit: aov(formula = Max_Chl ~ Treatment, data = max_bio)
# 
# $Treatment
#                        diff       lwr       upr     p adj
# 36pM-369pM         390.8033 -1240.276  2021.883 0.9327149
# 3.69pM-369pM     -2417.3467 -4048.426  -786.267 0.0040496
# 0.369pM-369pM    -3309.7200 -4835.455 -1783.985 0.0001726
# 0.0369pM-369pM   -4312.9433 -5944.023 -2681.864 0.0000273
# 3.69pM-36pM      -2808.1500 -4439.230 -1177.070 0.0012586
# 0.369pM-36pM     -3700.5233 -5226.259 -2174.788 0.0000619
# 0.0369pM-36pM    -4703.7467 -6334.826 -3072.667 0.0000118
# 0.369pM-3.69pM    -892.3733 -2418.109   633.362 0.3753586
# 0.0369pM-3.69pM  -1895.5967 -3526.676  -264.517 0.0211988
# 0.0369pM-0.369pM -1003.2233 -2528.959   522.512 0.2753904
```


